server:
  port: 9000

spring:
  application:
    name: ms-auth
  datasource:
    #url: jdbc:postgresql://localhost:5432/auth_db
    #username: postgres
    #password: qwerty123
    #url: jdbc:postgresql://localhost:26257/auth_db?user=root&password=
    #username: root
    #password:
    url: jdbc:postgresql://cockroachdb-node1:26257/auth?sslmode=disable
    username: root
    password: admin123 # Sin contraseña en modo insecure
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #properties:
    #  hibernate:
    #    show_sql: true
    #    format_sql: true
    #    dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  # instance:
  #  prefer-ip-address: true
  #  instance-id: ${spring.application.name}:${random.value}

#jwt:
#  secret: mysecretkey
#  expiration: 3600 # in seconds